# Generated by Django 3.2.5 on 2021-07-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='block',
            fields=[
                ('user', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cover_image', models.ImageField(upload_to='')),
                ('description_block', models.CharField(max_length=100)),
                ('developer', models.CharField(max_length=250)),
                ('rating', models.CharField(max_length=100)),
                ('download', models.CharField(max_length=100)),
                ('screenshots', models.ImageField(upload_to='')),
                ('review', models.CharField(max_length=100)),
                ('demo', models.ImageField(upload_to='')),
            ],
        ),
    ]
