# Generated by Django 3.2.5 on 2021-08-03 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='iso',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cover_image', models.ImageField(upload_to='')),
                ('description_iso', models.CharField(max_length=100)),
                ('developer', models.CharField(max_length=250)),
                ('rating', models.CharField(max_length=100)),
                ('download', models.CharField(max_length=100)),
                ('screenshots', models.ImageField(upload_to='')),
                ('review', models.CharField(max_length=100)),
                ('demo', models.ImageField(upload_to='')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='android',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cover_image', models.ImageField(upload_to='')),
                ('description_android', models.CharField(max_length=100)),
                ('developer', models.CharField(max_length=250)),
                ('rating', models.CharField(max_length=100)),
                ('download', models.CharField(max_length=100)),
                ('screenshots', models.ImageField(upload_to='')),
                ('review', models.CharField(max_length=100)),
                ('demo', models.ImageField(upload_to='')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
